name: julia
# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge
  
dependencies:
  # other packages
  - requests==2.32.3
  - traitlets==5.14.3

  # Required for issue #3057
  - xlrd==2.0.1

  # For https://github.com/berkeley-dsep-infra/datahub/issues/3079
  - websockify==0.12.0
